USE DATABASE BI;
USE SCHEMA ALERTS;

--
-- Check the recent spend missing possibly
--
SELECT B.ACCOUNT_NAME, A.*
FROM BI.ALERTS.BUYSIDE_ACCOUNT_DATA_TRACKING A
LEFT JOIN BI.COMMON.ACCOUNT_METADATA_MAPPINGS B
USING (BI_ACCOUNT_ID)
WHERE DATA_DATE BETWEEN CURRENT_DATE()-7 AND CURRENT_DATE()-2
AND SPEND_FORECAST > 100 -- threshold
AND SPEND_FOUND_TIME IS NULL
ORDER BY SPEND_FORECAST DESC
;

--
-- Check yesterday's spend missing possibly
--
SELECT B.ACCOUNT_NAME, A.* 
FROM BI.ALERTS.BUYSIDE_ACCOUNT_DATA_TRACKING A
LEFT JOIN BI.COMMON.ACCOUNT_METADATA_MAPPINGS B
USING (BI_ACCOUNT_ID)
WHERE DATA_DATE = CURRENT_DATE()-1
AND SPEND_FOUND_TIME IS NULL
ORDER BY SPEND_FORECAST DESC
;

--
-- Check recent 2 days spend seeming too low
--
SELECT B.ACCOUNT_NAME, A.*
FROM BI.ALERTS.BUYSIDE_ACCOUNT_DATA_TRACKING A
LEFT JOIN BI.COMMON.ACCOUNT_METADATA_MAPPINGS B
USING (BI_ACCOUNT_ID)
WHERE DATA_DATE >= CURRENT_DATE()-2
AND ALERT_STATUS = 1
ORDER BY SPEND_FORECAST DESC
;

--
-- Check yesterday's spend seeming OK
--
SELECT B.ACCOUNT_NAME, A.*
FROM BI.ALERTS.BUYSIDE_ACCOUNT_DATA_TRACKING A
LEFT JOIN BI.COMMON.ACCOUNT_METADATA_MAPPINGS B
USING (BI_ACCOUNT_ID)
WHERE DATA_DATE = CURRENT_DATE()-1
AND SPEND_FOUND_TIME IS NOT NULL
AND ALERT_STATUS = 0
ORDER BY SPEND_FORECAST DESC
;

--
-- Check yesterday's spend status over all acc (maybe partially in)
--
SELECT B.ACCOUNT_NAME, A.*
FROM BI.ALERTS.BUYSIDE_ACCOUNT_DATA_TRACKING A
LEFT JOIN BI.COMMON.ACCOUNT_METADATA_MAPPINGS B
USING (BI_ACCOUNT_ID)
WHERE DATA_DATE = CURRENT_DATE()-1
ORDER BY SPEND_FORECAST DESC
;


--
-- Check the problem rows related issue BI-1066
--
SELECT B.ACCOUNT_NAME, A.*
FROM BI.ALERTS.BUYSIDE_ACCOUNT_DATA_TRACKING A
LEFT JOIN BI.COMMON.ACCOUNT_METADATA_MAPPINGS B
USING (BI_ACCOUNT_ID)
WHERE (SPEND_ACTUAL = 0 OR SPEND_ACTUAL IS NULL)
AND SPEND_FOUND_TIME IS NOT NULL
ORDER BY SPEND_FORECAST DESC
;


--
-- Check today's spend data status
--
SELECT B.ACCOUNT_NAME, A.*
FROM BI.ALERTS.BUYSIDE_ACCOUNT_DATA_TRACKING A
LEFT JOIN BI.COMMON.ACCOUNT_METADATA_MAPPINGS B
USING (BI_ACCOUNT_ID)
WHERE DATA_DATE = CURRENT_DATE()
ORDER BY SPEND_FORECAST DESC
;
