USE SCHEMA BI.ALERTS;
USE SCHEMA BI_TEST.ALERTS;

--
-- Check the recent revenue missing possibly
--
SELECT B.CONTRACT_NAME, A.*
FROM ALERTS.SELLSIDE_CONTRACT_REVENUE_TRACKING A
LEFT JOIN BI.COMMON.SELLSIDE_CONTRACTS B
USING (CONTRACT_ID)
WHERE DATA_DATE BETWEEN CURRENT_DATE()-7 AND CURRENT_DATE()-1
AND REVENUE_FORECAST > 100 -- threshold
AND REVENUE_FOUND_TIME IS NULL
ORDER BY REVENUE_FORECAST DESC
;

--
-- Check yesterday's revenue missing possibly
--
SELECT B.CONTRACT_NAME, A.* 
FROM ALERTS.SELLSIDE_CONTRACT_REVENUE_TRACKING A
LEFT JOIN BI.COMMON.SELLSIDE_CONTRACTS B
USING (CONTRACT_ID)
WHERE DATA_DATE = CURRENT_DATE()-1
AND REVENUE_FOUND_TIME IS NULL
ORDER BY REVENUE_FORECAST DESC
;
